services:
  - type: web
    name: capstone-parking-frontend
    env: node
    nodeVersion: 18
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview -- --host 0.0.0.0 --port $PORT"
    envVars:
      - key: VITE_API_URL
        value: "https://capstone-parking-dodv.onrender.com/api/auth"