services:
  - type: web
    name: capstone-parking-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: VITE_API_URL
        value: "https://capstone-parking-dodv.onrender.com/api/auth"